-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;

-- ---
-- Table 'GENEROS'
-- 
-- ---

DROP TABLE IF EXISTS `GENEROS`;
		
CREATE TABLE `GENEROS` (
  `ID_Genero` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Genero` CHAR(100) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Genero`)
);

-- ---
-- Table 'PELICULAS'
-- 
-- ---

DROP TABLE IF EXISTS `PELICULAS`;
		
CREATE TABLE `PELICULAS` (
  `ID_Pelicula` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Pelicula` CHAR(100) NULL DEFAULT NULL,
  `Orden_Saga` DECIMAL NOT NULL DEFAULT NULL,
  `Duracion` TIME(2000) NOT NULL DEFAULT 'NULL',
  `Año_de_estreno` YEAR NOT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Pelicula`)
);

-- ---
-- Table 'IDIOMAS'
-- 
-- ---

DROP TABLE IF EXISTS `IDIOMAS`;
		
CREATE TABLE `IDIOMAS` (
  `ID_Idioma` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Idioma` CHAR(100) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Idioma`)
);

-- ---
-- Table 'PREMIO'
-- 
-- ---

DROP TABLE IF EXISTS `PREMIO`;
		
CREATE TABLE `PREMIO` (
  `ID_Premio` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Premio` CHAR(100) NOT NULL DEFAULT 'NULL',
  `Categoria` CHAR(100) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Premio`)
);

-- ---
-- Table 'PERSONAS'
-- 
-- ---

DROP TABLE IF EXISTS `PERSONAS`;
		
CREATE TABLE `PERSONAS` (
  `ID_Persona` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Persona` CHAR(100) NOT NULL DEFAULT 'NULL',
  `Edad` INTEGER(200) NOT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Persona`)
);

-- ---
-- Table 'PELICULAS_GENEROS'
-- 
-- ---

DROP TABLE IF EXISTS `PELICULAS_GENEROS`;
		
CREATE TABLE `PELICULAS_GENEROS` (
  `ID_Pelicula` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `ID_Genero` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Genero`)
);

-- ---
-- Table 'Lengua_PELICULAS_IDIOMAS'
-- 
-- ---

DROP TABLE IF EXISTS `Lengua_PELICULAS_IDIOMAS`;
		
CREATE TABLE `Lengua_PELICULAS_IDIOMAS` (
  `ID_Pelicula` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `ID_Idioma` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Idioma`)
);

-- ---
-- Table 'Subtitulos_PELICULAS_IDIOMAS'
-- 
-- ---

DROP TABLE IF EXISTS `Subtitulos_PELICULAS_IDIOMAS`;
		
CREATE TABLE `Subtitulos_PELICULAS_IDIOMAS` (
  `ID_Pelicula` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `ID_Idioma` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Idioma`)
);

-- ---
-- Table 'Titulos_PELICULAS_IDIOMAS'
-- 
-- ---

DROP TABLE IF EXISTS `Titulos_PELICULAS_IDIOMAS`;
		
CREATE TABLE `Titulos_PELICULAS_IDIOMAS` (
  `ID_Pelicula` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `ID_Idiomas` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Original` CHAR(100) NOT NULL DEFAULT 'NULL',
  `Nombre_en_este_idioma` CHAR(100) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Idiomas`)
);

-- ---
-- Table 'Gano_PELICULAS_PREMIOS'
-- 
-- ---

DROP TABLE IF EXISTS `Gano_PELICULAS_PREMIOS`;
		
CREATE TABLE `Gano_PELICULAS_PREMIOS` (
  `ID_Pelicula` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `ID_Premio` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Premio`)
);

-- ---
-- Table 'Habla_PERSONAS_IDIOMAS'
-- 
-- ---

DROP TABLE IF EXISTS `Habla_PERSONAS_IDIOMAS`;
		
CREATE TABLE `Habla_PERSONAS_IDIOMAS` (
  `ID_Persona` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `ID_Idioma` VARCHAR NULL AUTO_INCREMENT DEFAULT NULL,
  PRIMARY KEY (`ID_Persona`, `ID_Idioma`)
);

-- ---
-- Table 'Gano_PERSONA_PREMIO'
-- 
-- ---

DROP TABLE IF EXISTS `Gano_PERSONA_PREMIO`;
		
CREATE TABLE `Gano_PERSONA_PREMIO` (
  `ID_Premio` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `ID_Persona` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  PRIMARY KEY (`ID_Persona`, `ID_Premio`)
);

-- ---
-- Table 'Participacion_PELICULAS_PERSONAS'
-- 
-- ---

DROP TABLE IF EXISTS `Participacion_PELICULAS_PERSONAS`;
		
CREATE TABLE `Participacion_PELICULAS_PERSONAS` (
  `ID_Persona` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `ID_Pelicula` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `ID_Rol` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  PRIMARY KEY (`ID_Persona`, `ID_Pelicula`, `ID_Rol`)
);

-- ---
-- Table 'ROLES'
-- 
-- ---

DROP TABLE IF EXISTS `ROLES`;
		
CREATE TABLE `ROLES` (
  `ID_Rol` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Rol` CHAR(100) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Rol`)
);

-- ---
-- Foreign Keys 
-- ---

ALTER TABLE `GENEROS` ADD FOREIGN KEY (ID_Genero) REFERENCES `PELICULAS_GENEROS` (`ID_Genero`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `PELICULAS_GENEROS` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Lengua_PELICULAS_IDIOMAS` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Subtitulos_PELICULAS_IDIOMAS` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Titulos_PELICULAS_IDIOMAS` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Gano_PELICULAS_PREMIOS` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Participacion_PELICULAS_PERSONAS` (`ID_Pelicula`);
ALTER TABLE `IDIOMAS` ADD FOREIGN KEY (ID_Idioma) REFERENCES `Lengua_PELICULAS_IDIOMAS` (`ID_Idioma`);
ALTER TABLE `IDIOMAS` ADD FOREIGN KEY (ID_Idioma) REFERENCES `Subtitulos_PELICULAS_IDIOMAS` (`ID_Idioma`);
ALTER TABLE `IDIOMAS` ADD FOREIGN KEY (ID_Idioma) REFERENCES `Titulos_PELICULAS_IDIOMAS` (`ID_Idiomas`);
ALTER TABLE `IDIOMAS` ADD FOREIGN KEY (ID_Idioma) REFERENCES `Habla_PERSONAS_IDIOMAS` (`ID_Idioma`);
ALTER TABLE `PREMIO` ADD FOREIGN KEY (ID_Premio) REFERENCES `Gano_PELICULAS_PREMIOS` (`ID_Premio`);
ALTER TABLE `PREMIO` ADD FOREIGN KEY (ID_Premio) REFERENCES `Gano_PERSONA_PREMIO` (`ID_Premio`);
ALTER TABLE `PERSONAS` ADD FOREIGN KEY (ID_Persona) REFERENCES `Habla_PERSONAS_IDIOMAS` (`ID_Persona`);
ALTER TABLE `PERSONAS` ADD FOREIGN KEY (ID_Persona) REFERENCES `Gano_PERSONA_PREMIO` (`ID_Persona`);
ALTER TABLE `PERSONAS` ADD FOREIGN KEY (ID_Persona) REFERENCES `Participacion_PELICULAS_PERSONAS` (`ID_Persona`);
ALTER TABLE `ROLES` ADD FOREIGN KEY (ID_Rol) REFERENCES `Participacion_PELICULAS_PERSONAS` (`ID_Rol`);

-- ---
-- Table Properties
-- ---

-- ALTER TABLE `GENEROS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PELICULAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `IDIOMAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PREMIO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PERSONAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PELICULAS_GENEROS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Lengua_PELICULAS_IDIOMAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Subtitulos_PELICULAS_IDIOMAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Titulos_PELICULAS_IDIOMAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Gano_PELICULAS_PREMIOS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Habla_PERSONAS_IDIOMAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Gano_PERSONA_PREMIO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Participacion_PELICULAS_PERSONAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `ROLES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ---
-- Test Data
-- ---

-- INSERT INTO `GENEROS` (`ID_Genero`,`Nombre_Genero`) VALUES
-- ('','');
-- INSERT INTO `PELICULAS` (`ID_Pelicula`,`Nombre_Pelicula`,`Orden_Saga`,`Duracion`,`Año_de_estreno`) VALUES
-- ('','','','','');
-- INSERT INTO `IDIOMAS` (`ID_Idioma`,`Nombre_Idioma`) VALUES
-- ('','');
-- INSERT INTO `PREMIO` (`ID_Premio`,`Nombre_Premio`,`Categoria`) VALUES
-- ('','','');
-- INSERT INTO `PERSONAS` (`ID_Persona`,`Nombre_Persona`,`Edad`) VALUES
-- ('','','');
-- INSERT INTO `PELICULAS_GENEROS` (`ID_Pelicula`,`ID_Genero`) VALUES
-- ('','');
-- INSERT INTO `Lengua_PELICULAS_IDIOMAS` (`ID_Pelicula`,`ID_Idioma`) VALUES
-- ('','');
-- INSERT INTO `Subtitulos_PELICULAS_IDIOMAS` (`ID_Pelicula`,`ID_Idioma`) VALUES
-- ('','');
-- INSERT INTO `Titulos_PELICULAS_IDIOMAS` (`ID_Pelicula`,`ID_Idiomas`,`Nombre_Original`,`Nombre_en_este_idioma`) VALUES
-- ('','','','');
-- INSERT INTO `Gano_PELICULAS_PREMIOS` (`ID_Pelicula`,`ID_Premio`) VALUES
-- ('','');
-- INSERT INTO `Habla_PERSONAS_IDIOMAS` (`ID_Persona`,`ID_Idioma`) VALUES
-- ('','');
-- INSERT INTO `Gano_PERSONA_PREMIO` (`ID_Premio`,`ID_Persona`) VALUES
-- ('','');
-- INSERT INTO `Participacion_PELICULAS_PERSONAS` (`ID_Persona`,`ID_Pelicula`,`ID_Rol`) VALUES
-- ('','','');
-- INSERT INTO `ROLES` (`ID_Rol`,`Nombre_Rol`) VALUES
-- ('','');