-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;

-- ---
-- Table 'GENEROS'
-- 
-- ---

DROP TABLE IF EXISTS `GENEROS`;
		
CREATE TABLE `GENEROS` (
  `ID_Genero` VARCHAR(32) NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Genero` VARCHAR(100) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Genero`)
);

-- ---
-- Table 'PELICULAS'
-- 
-- ---

DROP TABLE IF EXISTS `PELICULAS`;
		
CREATE TABLE `PELICULAS` (
  `ID_Pelicula` VARCHAR(32) NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Pelicula` VARCHAR(100) NOT NULL DEFAULT 'NULL',
  `Orden_Saga` DECIMAL(32) NOT NULL DEFAULT NULL,
  `Duracion` INTEGER(10000) NOT NULL DEFAULT NULL,
  `Año_de_Estreno` YEAR NOT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Pelicula`)
);

-- ---
-- Table 'IDIOMA'
-- 
-- ---

DROP TABLE IF EXISTS `IDIOMA`;
		
CREATE TABLE `IDIOMA` (
  `ID_Idioma` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Idioma` VARCHAR(100) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Idioma`)
);

-- ---
-- Table 'PERSONAJE'
-- 
-- ---

DROP TABLE IF EXISTS `PERSONAJE`;
		
CREATE TABLE `PERSONAJE` (
  `ID_Personaje` VARCHAR(32) NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Personaje` VARCHAR(100) NOT NULL DEFAULT 'NULL',
  `Rol` CHAR(100) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Personaje`)
);

-- ---
-- Table 'PREMIOS'
-- 
-- ---

DROP TABLE IF EXISTS `PREMIOS`;
		
CREATE TABLE `PREMIOS` (
  `ID_Premio` VARCHAR(32) NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Premio` VARCHAR(100) NOT NULL DEFAULT 'NULL',
  `Categoria` VARCHAR(100) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Premio`)
);

-- ---
-- Table 'PERSONA'
-- 
-- ---

DROP TABLE IF EXISTS `PERSONA`;
		
CREATE TABLE `PERSONA` (
  `ID_Persona` VARCHAR NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Persona` VARCHAR NOT NULL DEFAULT 'NULL',
  `Edad` INT(200) NOT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Persona`)
);

-- ---
-- Table 'CANCIONES'
-- 
-- ---

DROP TABLE IF EXISTS `CANCIONES`;
		
CREATE TABLE `CANCIONES` (
  `ID_Cancion` VARCHAR(32) NOT NULL DEFAULT 'NULL',
  `Nombre_Cancion` VARCHAR(100) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Cancion`)
);

-- ---
-- Table 'BANDA SONORA'
-- 
-- ---

DROP TABLE IF EXISTS `BANDA SONORA`;
		
CREATE TABLE `BANDA SONORA` (
  `ID_Banda_Sonora` VARCHAR(32) NOT NULL AUTO_INCREMENT DEFAULT 'NULL',
  `Nombre_Banda_Sonora` VARCHAR(100) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Banda_Sonora`)
);

-- ---
-- Table 'Peliculas_Generos'
-- 
-- ---

DROP TABLE IF EXISTS `Peliculas_Generos`;
		
CREATE TABLE `Peliculas_Generos` (
  `ID_Genero` VARCHAR(32) NOT NULL DEFAULT 'NULL',
  `ID_Pelicula` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Genero`, `ID_Pelicula`)
);

-- ---
-- Table 'Lengua_PELICULAS_IDIOMAS'
-- 
-- ---

DROP TABLE IF EXISTS `Lengua_PELICULAS_IDIOMAS`;
		
CREATE TABLE `Lengua_PELICULAS_IDIOMAS` (
  `ID_Pelicula` VARCHAR NOT NULL DEFAULT 'NULL',
  `ID_Idioma` VARCHAR NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Idioma`)
);

-- ---
-- Table 'Subtitulos_PELICULAS_IDIOMAS'
-- 
-- ---

DROP TABLE IF EXISTS `Subtitulos_PELICULAS_IDIOMAS`;
		
CREATE TABLE `Subtitulos_PELICULAS_IDIOMAS` (
  `ID_Pelicula` VARCHAR NOT NULL DEFAULT 'NULL',
  `ID_Idioma` VARCHAR NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Idioma`)
);

-- ---
-- Table 'Titulos_PELICULAS_IDIOMAS'
-- 
-- ---

DROP TABLE IF EXISTS `Titulos_PELICULAS_IDIOMAS`;
		
CREATE TABLE `Titulos_PELICULAS_IDIOMAS` (
  `ID_Pelicula` VARCHAR NOT NULL DEFAULT 'NULL',
  `ID_Idioma` VARCHAR NOT NULL DEFAULT 'NULL',
  `Nombre_Original` CHAR(2) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Idioma`)
);

-- ---
-- Table 'Dirige_PELICULAS_PERSONAS'
-- 
-- ---

DROP TABLE IF EXISTS `Dirige_PELICULAS_PERSONAS`;
		
CREATE TABLE `Dirige_PELICULAS_PERSONAS` (
  `ID_Pelicula` VARCHAR NOT NULL DEFAULT 'NULL',
  `ID_Persona` VARCHAR NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Persona`)
);

-- ---
-- Table 'Participa_PELICULAS_PERSONAJES'
-- 
-- ---

DROP TABLE IF EXISTS `Participa_PELICULAS_PERSONAJES`;
		
CREATE TABLE `Participa_PELICULAS_PERSONAJES` (
  `ID_Pelicula` VARCHAR NOT NULL DEFAULT 'NULL',
  `ID_Personaje` VARCHAR NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Personaje`)
);

-- ---
-- Table 'Gano_PELICULAS_PREMIOS'
-- 
-- ---

DROP TABLE IF EXISTS `Gano_PELICULAS_PREMIOS`;
		
CREATE TABLE `Gano_PELICULAS_PREMIOS` (
  `ID_Pelicula` VARCHAR NOT NULL DEFAULT 'NULL',
  `ID_Premio` VARCHAR NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Premio`)
);

-- ---
-- Table 'Nominado_PELICULAS_PREMIOS'
-- 
-- ---

DROP TABLE IF EXISTS `Nominado_PELICULAS_PREMIOS`;
		
CREATE TABLE `Nominado_PELICULAS_PREMIOS` (
  `ID_Pelicula` VARCHAR NOT NULL DEFAULT 'NULL',
  `ID_Premios` VARCHAR NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID_Pelicula`, `ID_Premios`)
);

-- ---
-- Foreign Keys 
-- ---

ALTER TABLE `GENEROS` ADD FOREIGN KEY (ID_Genero) REFERENCES `Peliculas_Generos` (`ID_Genero`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Peliculas_Generos` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Lengua_PELICULAS_IDIOMAS` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Subtitulos_PELICULAS_IDIOMAS` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Titulos_PELICULAS_IDIOMAS` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Dirige_PELICULAS_PERSONAS` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Participa_PELICULAS_PERSONAJES` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Gano_PELICULAS_PREMIOS` (`ID_Pelicula`);
ALTER TABLE `PELICULAS` ADD FOREIGN KEY (ID_Pelicula) REFERENCES `Nominado_PELICULAS_PREMIOS` (`ID_Pelicula`);
ALTER TABLE `IDIOMA` ADD FOREIGN KEY (ID_Idioma) REFERENCES `Lengua_PELICULAS_IDIOMAS` (`ID_Idioma`);
ALTER TABLE `IDIOMA` ADD FOREIGN KEY (ID_Idioma) REFERENCES `Subtitulos_PELICULAS_IDIOMAS` (`ID_Idioma`);
ALTER TABLE `IDIOMA` ADD FOREIGN KEY (ID_Idioma) REFERENCES `Titulos_PELICULAS_IDIOMAS` (`ID_Idioma`);
ALTER TABLE `PERSONAJE` ADD FOREIGN KEY (ID_Personaje) REFERENCES `Participa_PELICULAS_PERSONAJES` (`ID_Personaje`);
ALTER TABLE `PREMIOS` ADD FOREIGN KEY (ID_Premio) REFERENCES `Gano_PELICULAS_PREMIOS` (`ID_Premio`);
ALTER TABLE `PREMIOS` ADD FOREIGN KEY (ID_Premio) REFERENCES `Nominado_PELICULAS_PREMIOS` (`ID_Premios`);
ALTER TABLE `PERSONA` ADD FOREIGN KEY (ID_Persona) REFERENCES `Dirige_PELICULAS_PERSONAS` (`ID_Persona`);

-- ---
-- Table Properties
-- ---

-- ALTER TABLE `GENEROS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PELICULAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `IDIOMA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PERSONAJE` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PREMIOS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PERSONA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CANCIONES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `BANDA SONORA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Peliculas_Generos` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Lengua_PELICULAS_IDIOMAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Subtitulos_PELICULAS_IDIOMAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Titulos_PELICULAS_IDIOMAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Dirige_PELICULAS_PERSONAS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Participa_PELICULAS_PERSONAJES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Gano_PELICULAS_PREMIOS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Nominado_PELICULAS_PREMIOS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ---
-- Test Data
-- ---

-- INSERT INTO `GENEROS` (`ID_Genero`,`Nombre_Genero`) VALUES
-- ('','');
-- INSERT INTO `PELICULAS` (`ID_Pelicula`,`Nombre_Pelicula`,`Orden_Saga`,`Duracion`,`Año_de_Estreno`) VALUES
-- ('','','','','');
-- INSERT INTO `IDIOMA` (`ID_Idioma`,`Nombre_Idioma`) VALUES
-- ('','');
-- INSERT INTO `PERSONAJE` (`ID_Personaje`,`Nombre_Personaje`,`Rol`) VALUES
-- ('','','');
-- INSERT INTO `PREMIOS` (`ID_Premio`,`Nombre_Premio`,`Categoria`) VALUES
-- ('','','');
-- INSERT INTO `PERSONA` (`ID_Persona`,`Nombre_Persona`,`Edad`) VALUES
-- ('','','');
-- INSERT INTO `CANCIONES` (`ID_Cancion`,`Nombre_Cancion`) VALUES
-- ('','');
-- INSERT INTO `BANDA SONORA` (`ID_Banda_Sonora`,`Nombre_Banda_Sonora`) VALUES
-- ('','');
-- INSERT INTO `Peliculas_Generos` (`ID_Genero`,`ID_Pelicula`) VALUES
-- ('','');
-- INSERT INTO `Lengua_PELICULAS_IDIOMAS` (`ID_Pelicula`,`ID_Idioma`) VALUES
-- ('','');
-- INSERT INTO `Subtitulos_PELICULAS_IDIOMAS` (`ID_Pelicula`,`ID_Idioma`) VALUES
-- ('','');
-- INSERT INTO `Titulos_PELICULAS_IDIOMAS` (`ID_Pelicula`,`ID_Idioma`,`Nombre_Original`) VALUES
-- ('','','');
-- INSERT INTO `Dirige_PELICULAS_PERSONAS` (`ID_Pelicula`,`ID_Persona`) VALUES
-- ('','');
-- INSERT INTO `Participa_PELICULAS_PERSONAJES` (`ID_Pelicula`,`ID_Personaje`) VALUES
-- ('','');
-- INSERT INTO `Gano_PELICULAS_PREMIOS` (`ID_Pelicula`,`ID_Premio`) VALUES
-- ('','');
-- INSERT INTO `Nominado_PELICULAS_PREMIOS` (`ID_Pelicula`,`ID_Premios`) VALUES
-- ('','');